title: 王梦越的博客
url: "https://wangmengyue07.github.io"
baseurl: "/wangmengyue08.github.io"
email:
description: >-
  一个编程初学者的学习笔记和成长记录
twitter_username:
github_username: wangmengyue07
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:year/:month/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Shanghai

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "王梦越"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "编程初学者，正在学习的路上"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wangmengyue07"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wangmengyue07"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
